# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-07 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingExample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataoutput', models.FloatField(blank=True, null=True)),
                ('datainput', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='annconfiguration',
            name='x_value',
        ),
        migrations.RemoveField(
            model_name='annconfiguration',
            name='y_value',
        ),
    ]
