# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-12 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filter', '0004_kalmanresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='annresult',
            name='function',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
