# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-07 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ANNConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layers', models.IntegerField(blank=True, null=True)),
                ('activation', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('x_value', models.FloatField(blank=True, null=True)),
                ('y_value', models.FloatField(blank=True, null=True)),
                ('learning_rate', models.IntegerField(blank=True, null=True)),
                ('epochs', models.IntegerField(blank=True, null=True)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading', models.FloatField(blank=True, null=True)),
                ('prevreading', models.FloatField(blank=True, null=True)),
                ('output', models.FloatField(blank=True, null=True)),
                ('error', models.FloatField(blank=True, null=True)),
                ('truevalue', models.FloatField(blank=True, null=True)),
                ('kalmanvalue', models.FloatField(blank=True, null=True)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='KalmanConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_value', models.FloatField(blank=True, null=True)),
                ('iterations', models.FloatField(blank=True, null=True)),
                ('initial_guess', models.FloatField(blank=True, null=True)),
                ('posteri_estimate', models.FloatField(blank=True, null=True)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
